config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :user
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to:'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :category  do
    resources :article, only: [:show]
  end
  resources :article, except: [:show] do
    resources :vote, only: [:create,:destroy]
  end
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  has_attached_file :image

  validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png']
  belongs_to :user
  belongs_to :category
  has_many :votes, dependent: :destroy
end

app/controllers/article_controller.rb
class ArticleController < ApplicationController
  before_action :login_required, only: %i[new create destroy]
  def new; end

  def create
    @article = Article.new(article_params)
    @article[:user_id] = current_user.id
    if @article.save
      flash[:notice] = 'Article created successfully!'
    else
      flash[:alert] = 'Failed to create article please try again!'
    end
    redirect_to root_path
  end

  def article_params
    params.require(:article).permit(:title, :body, :category_id, :image)
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/article/new.html.erb
<h1 class="page-title">Create New Article:</h1>
<%= form_with model: @article, url: article_index_path,html: {multipart: true}, class: "creation-form" do |a|%>
  Enter Article title: <br>
  <%= text_field(:article, :title)%> <br> <br>
  Enter the content of the Article: <br><br>
  <%= text_area :article, :body, rows: 10, cols: 50%> <br><br>
  Enter a category for this article: <br>
  <%= collection_select(:article,:category_id, Category.all, :id, :name) %> <br><br>
  Attach an Image<br />
  <%= file_field(:article,:image) %> <br> <br>
  <%= a.submit "Submit Article"%>
<% end %>